### ISSUE TITLE
Incomplete query is sent automatically

### ISSUE THREAD

**Issue by graue70** [ad-freiburg/aqqu-frontend#8]
I try to write the following query into the input field: `What author wrote the book "What Would Joey Do?"?` (This is an example query from [SimpleQuestions](https://github.com/davidgolub/SimpleQA/blob/master/datasets/SimpleQuestions/annotated_fb_data_test.txt).)

When I put the first question mark (which is part of the [book title](https://www.wikidata.org/wiki/Q7991448)), the request is sent automatically. The input field is deactivated until the request is finished and the answer is shown. If I then complete the query, the request is sent again when I type the second question mark.

In this particular example, the answer to the incomplete query is correct, but it is easy to imagine examples where this is not the case.

This raises the question whether the UX advantage of automatically sending a request when a question mark is typed actually outweighs the UX catastrophe in the few cases where a question mark is part of an entity (e.g. film titles, song titles, album titles).

Another argument against automatically sending the request is a comparison with other services using a single text box as input (e.g. google search). I think I've never experienced a service which automatically sends a request without the user pressing Enter. Because of this, users might even be confused by the automatic request in normal cases.

**Comment by hannahbast** [comment]
This is my fault :-)

When playing around with an earlier version of the UI, I found it annoying that at the end of a question you press enter to complete to a question mark and then you have to press a key (or click on the "Ask" button) **again** to obtain the answer. This is obviously undesired behaviour.

There is an obvious fix to the problem you just pointed out: only launch the question when the "?" has been selected from the completions, not when it is typed or pasted explicitly

**Comment by flackbash** [comment]
I implemented this in fc6ee764 . The question is now only submitted if "?" was selected from the completion suggestions.
